# Generated by Django 3.2.7 on 2021-09-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_checkin', models.AutoField(primary_key=True, serialize=False)),
                ('hora_checkin', models.TimeField(null=True)),
                ('data_checkin', models.DateField()),
                ('responsavel_checkin', models.CharField(max_length=100)),
                ('status_checkin', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Checkins',
                'db_table': 'CheckIn',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_checkout', models.AutoField(primary_key=True, serialize=False)),
                ('hora_checkout', models.TimeField(null=True)),
                ('data_checkout', models.DateField()),
                ('responsavel_checkout', models.CharField(max_length=100)),
                ('status_checkout', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Checkouts',
                'db_table': 'Checkout',
            },
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id_limpeza', models.AutoField(primary_key=True, serialize=False)),
                ('hora_limpeza', models.TimeField(null=True)),
                ('data_limpeza', models.DateField()),
                ('status_limpeza', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Limpezas',
                'db_table': 'Limpeza',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id_locacao', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='userCalendar.checkin')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='userCalendar.checkout')),
                ('limpeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza', to='userCalendar.limpeza')),
            ],
            options={
                'verbose_name_plural': 'Locacoes',
                'db_table': 'Locacao',
            },
        ),
    ]
