# Generated by Django 3.2.7 on 2021-09-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_checkin', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(max_length=10)),
                ('data_checkin', models.DateField()),
                ('hora_checkin', models.TimeField(null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('numero_usuario', models.CharField(max_length=25)),
                ('quatidade_adultos', models.IntegerField()),
                ('quatidade_criancas', models.IntegerField()),
                ('quantidade_pet', models.IntegerField()),
                ('quantidade_diarias', models.IntegerField()),
                ('valor_a_pagar', models.IntegerField()),
                ('ja_pago', models.BooleanField()),
                ('status', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Checkins',
                'db_table': 'CheckIn',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_checkout', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(max_length=10)),
                ('data_checkin', models.DateField()),
                ('hora_checkin', models.TimeField(null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('numero_usuario', models.CharField(max_length=25)),
                ('quantidade_diarias', models.IntegerField()),
                ('valor_a_pagar', models.IntegerField()),
                ('ja_pago', models.BooleanField()),
                ('status', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Checkouts',
                'db_table': 'Checkout',
            },
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id_limpeza', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_limpeza', models.TimeField(null=True)),
                ('data_limpeza', models.DateField()),
                ('status_limpeza', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Limpezas',
                'db_table': 'Limpeza',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id_locacao', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='userCalendar.checkin')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='userCalendar.checkout')),
                ('limpeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza', to='userCalendar.limpeza')),
            ],
            options={
                'verbose_name_plural': 'Locacoes',
                'db_table': 'Locacao',
            },
        ),
    ]
