# Generated by Django 3.2.7 on 2021-09-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='valor_a_pagar',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='valor_a_pagar',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
