# Generated by Django 3.2.7 on 2021-09-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'Checkins'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'Checkouts'},
        ),
        migrations.AlterModelOptions(
            name='controle',
            options={'verbose_name_plural': 'Controles'},
        ),
        migrations.AlterModelOptions(
            name='limpeza',
            options={'verbose_name_plural': 'Limpezas'},
        ),
    ]
