# Generated by Django 3.2.7 on 2021-09-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0002_auto_20210915_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='valor_a_pagar',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
