# Generated by Django 3.2.7 on 2021-09-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0002_auto_20210911_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'Checkinss'},
        ),
    ]
