# Generated by Django 3.2.7 on 2021-09-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0003_alter_checkin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'Checkins'},
        ),
    ]
