# Generated by Django 3.2.7 on 2021-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0004_alter_checkin_valor_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='valor_a_pagar',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='valor_a_pagar',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
