# Generated by Django 3.2.7 on 2021-09-15 23:28

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0006_auto_20210915_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='valor_a_pagar',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='valor_a_pagar',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
    ]
