# Generated by Django 3.2.7 on 2021-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCalendar', '0007_auto_20210915_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='data_checkin',
            new_name='data_checkou',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='hora_checkin',
        ),
        migrations.AddField(
            model_name='checkout',
            name='hora_checkou',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='limpeza',
            name='id_limpeza',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
