# Generated by Django 3.2.7 on 2021-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitriao',
            fields=[
                ('id_anfitriao', models.AutoField(primary_key=True, serialize=False)),
                ('cpd_anfitriao', models.CharField(max_length=11)),
                ('name_anfitriao', models.CharField(max_length=50)),
                ('date_year_anfitriao', models.DateField(null=True)),
                ('email_anfitriao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Anfitrioes',
                'db_table': 'Anfitriao',
            },
        ),
    ]
